sonar.projectKey=ecommerce-devops
sonar.projectName=NovaStore E-Commerce
sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/tests
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js,**/test-helper.js
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
