apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: novestore-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rayyan12311/novastore-be:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: backend-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 5
