apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: novestore-ns
data:
  PORT: "5001"
  HOST: "0.0.0.0"
  NODE_ENV: "production"
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "postgrespassword"
  DB_NAME: "ecommerce"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgress-config
  namespace: novestore-ns
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgrespassword"
  POSTGRES_DB: "ecommerce"
